### PR TITLE
Fr changes

### PR DESCRIPTION
**Pull request by Aliquanto3**
A bunch of changes required in Modern, specifically changes for the new URx Breach value piles. 
Tried the compare option to make sure that everything works.

### CODE REVIEW

**Comment by Badaro** [comment]
@Aliquanto3 This has legacy stuff as well, I assume this is intentional?

**Comment by Aliquanto3** [comment]
Yes, since you told me to always push the changes I make ^^
There aren't any conflict/unknown with those over the year thanks to those latest changes, however an improvement will be required for the old results.

**Comment by Badaro** [comment]
@Aliquanto3 The changes fix way more things than they break so I say you can go ahead and merge them. However, I noticed it breaks some Titan lists.

* modern-preliminary-2022-10-0312480086 -> matyo804 changed from Amulet Titan to Unknown
* modern-preliminary-2022-12-2712504255 -> midwestmages changed from Breach Titan to Unknown
* modern-preliminary-2022-12-2812504263 -> midwestmages changed from Breach Titan to Unknown

This should probably be reviewed at a later time.

**Comment by Aliquanto3** [comment]
Ah, right, I had an issue with a Titan Reanimator list, I will need to find another way to handle it.

**Pull request merged**
