### PR TITLE
merge all UWX control in the generic archetype or a specific one

### PR DESCRIPTION
**Pull request by YrielPenguin**
Azorious controls list are splitted based on the presence or not of Narset, Parter of the Veils and/or Day's Undoing.
Which doesn't make sense in my opinion because both decks are the same shell currently with small changes.

### CODE REVIEW

**Comment by Badaro** [comment]
If we're combining these I feel it's better to just drop the "Azorius Control" definition and rely only on the fallback. Why do you feel that one is necessary?

Also, I *really* dislike using color names like "Azorius" in archetype definitions unless they're automatically assigned by the `IncludeColorInName` flag. 

When you create an archetype like this you consolidate all color splashes into a single thing, and if that's the case I think it's incorrect to be naming after colors. So if we decide to continue like this I feel we should at least change the name to `Teferi Control` or something.

**Comment by YrielPenguin** [comment]
I don't mind about mind, "Solitude Control" or "Teferi Control" seems good indeed.

Ok I will try to reduce the DoesNotContain to stay away from Omnath piles mainly I guess.

**Comment by Badaro** [comment]
You don't need to change the DoesNotContain clauses right now, changing the name would be enough for me to merge this now, and you can review that later.

Also that was more of a recommendation in the lines of "if you have a lot of these it might be better to review this". In some cases there you may not have a better solution, but that often indicates multiple archetypes that need to be combined either with fallbacks or variants.

**Comment by Aliquanto3** [comment]
Currently discussing it on the Modern [FR] Discord to be faster than on Github ^^
Agreed with all your comments. I am not sure how to deal with 4c though, but something indeed has to be done.
I am not super fan of the name "Solitude Control" either.

**Comment by Badaro** [comment]
@Aliquanto3 let me know the consensus you reach.

**Comment by Badaro** [comment]
@Aliquanto3 @YrielPenguin My $0.02. After running some tests I'd suggest simply doing this:

* Delete NarsetCombo
* Delete Miracles
* Rely on the existing fallback for non-Omnath Control decks.

The color detection algorithm requires *both* lands and spells to consider a color, so simply adding some Triomes for Binding won't change the deck from Azorius to another color combination. 

There's some lists as Jeskai since they include spells such as Fire/Ice, but it's a small amount (<10%) and I personally don't think it's worth the effort to declare a new archetype just to combine those.

**Comment by Badaro** [comment]
Due to the lack of answers I'm going to close this one without merging, and instead push the changes I suggested above since I think it achieves the desired effect with less effort.

Feel free to test my changes and make a new PR with other potential improvements.

**Comment by Badaro** [comment]
Changes pushed: https://github.com/Badaro/MTGOFormatData/commit/05cbc4a7c0be61c1069953d3381e48694f4d080f

**Comment by Badaro** [comment]
Deleting these "redundant" archetypes also goes in the direction I'm with #60 and #61 - simplify the archetype rules for easier maintenance, in particular we have MH3 coming which may require a lot of changes.

**Pull request closed without merging**
