### PR TITLE
New Format: Standard

### PR DESCRIPTION
**Pull request by Jiliac**
Adding the Standard format.

### CODE REVIEW

**Comment by Badaro** [comment]
> The Midrange decks are difficult to pinpoint. I tried to create archetypes for them but we might be better off just relying on fallbacks.

That's a very common problem with Midrange, and one of the main reasons I ended with the fallbacks as an option.

**Comment by Badaro** [comment]
Mind adding yourself to the readme as the one who did the Standard definitions? I think that's all I need to approve this one.

**Comment by Jiliac** [comment]
Done ✅  Thanks :)

**Comment by Badaro** [comment]
Thanks. Merged. 

We may need to look into a different naming for Standard in the future due to the rotating nature (maybe something like "Standard-2024"?), but we'll worry about that after rotation.

**Pull request merged**
