### PR TITLE
[Legacy] Fix Storm Decks

### PR DESCRIPTION
**Pull request by alex-mckinley**
[Legacy] Remove storm.json
[Legacy] add ANT, Black Saga Storm, Ruby Storm, TEG, and TES

Hi! I am from TheEPICStorm.com website team and we were working on integrating this project into our Discord. I noticed that the storm definitions for Legacy were a bit off so here's an update.

### CODE REVIEW

**Comment by Badaro** [comment]
@Jiliac I think you're the most active on Legacy nowadays, can you review this and see if you want any changes before merging?

**Comment by Badaro** [comment]
From a quick glance, there's already a "Storm" archetype that seems to be superceded by this change? So I think we at least would need to remove that one.

**Comment by alex-mckinley** [comment]
I thought I had removed the file, I can add

**Review by Badaro — APPROVED** [review]

**Comment by Badaro** [comment]
Jiliac is probably busy so I'm merging this. :) Worst-case we can make adjustments later.

**Comment by Jiliac** [comment]
Hey @alex-mckinley ! Sorry I didn't see the notification earlier.

Thanks a lot for your contribution 🤗 

My only worry is the high granularity. Splitting different versions can make the sample size of all archetypes too low, and then all the data point we have are too "noisy" to be significant.

For this reason, we sometimes keep "versions" of the same deck gathered together to have more significant data points. However, I know in Vintage `@IamActuallyLvL1` prefers to be as refined as possible in the archetype definition, and then does some post-processing to have some "buckets" of archetypes and sub-archetypes. So IDK what you prefer here.

Also I wouldn't know about legacy and storm in particular to know which decks have similar enough game plan to be gathered together.

**Other minor point:** Can shorten `Echo Bowmasters Black Saga Storm`? Maybe removing the "black"?

**Pull request merged**
